package paises

var (
	UltimaModificacion = "6-mayo-2025"

	// Codigos de países, Nombre
	// ejemplo: "AF" -> "Afganistán"

	IndexPaises = map[string]string{
		"AF": "Afganistán",
		"AL": "Albania",
		"DZ": "Argelia",
		"AS": "Samoa Americana",
		"AD": "Andorra",
		"AO": "Angola",
		"AI": "Anguila",
		"AQ": "Antártida",
		"AG": "Antigua y Barbuda",
		"AR": "Argentina",
		"AM": "Armenia",
		"AW": "Aruba",
		"AU": "Australia",
		"AT": "Austria",
		"AZ": "Azerbaiyán",
		"BS": "Bahamas",
		"BH": "Bahrein",
		"BD": "Bangladesh",
		"BB": "Barbados",
		"BY": "Bielorrusia",
		"BE": "Bélgica",
		"BZ": "Belice",
		"BJ": "Benín",
		"BM": "Bermudas",
		"BT": "Bután",
		"BO": "Bolivia",
		"BA": "Bosnia y Herzegovina",
		"BW": "Botswana",
		"BV": "Isla Bouvet",
		"BR": "Brasil",
		"IO": "Territorio Británico del Océano Índico",
		"BN": "Brunéi Darussalam",
		"BG": "Bulgaria",
		"BF": "Burkina Faso",
		"BI": "Burundi",
		"KH": "Camboya",
		"CM": "Camerún",
		"CA": "Canadá",
		"CV": "Cabo Verde",
		"KY": "Islas Caimán",
		"CF": "República Centroafricana",
		"TD": "Chad",
		"CL": "Chile",
		"CN": "China",
		"CX": "Isla de Navidad",
		"CC": "Islas Cocos (Keeling)",
		"CO": "Colombia",
		"KM": "Comoras",
		"CG": "Congo",
		"CD": "República Democrática del Congo",
		"CK": "Islas Cook",
		"CR": "Costa Rica",
		"CI": "Costa de Marfil",
		"HR": "Croacia",
		"CU": "Cuba",
		"CY": "Chipre",
		"CZ": "República Checa",
		"DK": "Dinamarca",
		"DJ": "Yibuti",
		"DM": "Dominica",
		"DO": "República Dominicana",
		"EC": "Ecuador",
		"EG": "Egipto",
		"SV": "El Salvador",
		"GQ": "Guinea Ecuatorial",
		"ER": "Eritrea",
		"EE": "Estonia",
		"ET": "Etiopía",
		"FK": "Islas Malvinas",
		"FO": "Islas Feroe",
		"FJ": "Fiyi",
		"FI": "Finlandia",
		"FR": "Francia",
		"GF": "Guayana Francesa",
		"PF": "Polinesia Francesa",
		"TF": "Tierras Australes Francesas",
		"GA": "Gabón",
		"GM": "Gambia",
		"GE": "Georgia",
		"DE": "Alemania",
		"GH": "Ghana",
		"GI": "Gibraltar",
		"GR": "Grecia",
		"GL": "Groenlandia",
		"GD": "Granada",
		"GP": "Guadalupe",
		"GU": "Guam",
		"GT": "Guatemala",
		"GN": "Guinea",
		"GW": "Guinea-Bissau",
		"GY": "Guyana",
		"HT": "Haití",
		"HM": "Isla Heard e Islas McDonald",
		"VA": "Ciudad del Vaticano",
		"HN": "Honduras",
		"HK": "Hong Kong",
		"HU": "Hungría",
		"IS": "Islandia",
		"IN": "India",
		"ID": "Indonesia",
		"IR": "Irán",
		"IQ": "Irak",
		"IE": "Irlanda",
		"IL": "Israel",
		"IT": "Italia",
		"JM": "Jamaica",
		"JP": "Japón",
		"JO": "Jordania",
		"KZ": "Kazajistán",
		"KE": "Kenia",
		"KI": "Kiribati",
		"KP": "Corea del Norte",
		"KR": "Corea del Sur",
		"KW": "Kuwait",
		"KG": "Kirguistán",
		"LA": "Laos",
		"LV": "Letonia",
		"LB": "Líbano",
		"LS": "Lesoto",
		"LR": "Liberia",
		"LY": "Libia",
		"LI": "Liechtenstein",
		"LT": "Lituania",
		"LU": "Luxemburgo",
		"MO": "Macao",
		"MK": "Macedonia del Norte",
		"MG": "Madagascar",
		"MW": "Malawi",
		"MY": "Malasia",
		"MV": "Maldivas",
		"ML": "Malí",
		"MT": "Malta",
		"MH": "Islas Marshall",
		"MQ": "Martinica",
		"MR": "Mauritania",
		"MU": "Mauricio",
		"YT": "Mayotte",
		"MX": "México",
		"FM": "Micronesia",
		"MD": "Moldavia",
		"MC": "Mónaco",
		"MN": "Mongolia",
		"MS": "Montserrat",
		"MA": "Marruecos",
		"MZ": "Mozambique",
		"MM": "Myanmar",
		"NA": "Namibia",
		"NR": "Nauru",
		"NP": "Nepal",
		"NL": "Países Bajos",
		"NC": "Nueva Caledonia",
		"NZ": "Nueva Zelanda",
		"NI": "Nicaragua",
		"NE": "Níger",
		"NG": "Nigeria",
		"NU": "Niue",
		"NF": "Isla Norfolk",
		"MP": "Islas Marianas del Norte",
		"NO": "Noruega",
		"OM": "Omán",
		"PK": "Pakistán",
		"PW": "Palaos",
		"PS": "Palestina",
		"PA": "Panamá",
		"PG": "Papúa Nueva Guinea",
		"PY": "Paraguay",
		"PE": "Perú",
		"PH": "Filipinas",
		"PN": "Pitcairn",
		"PL": "Polonia",
		"PT": "Portugal",
		"PR": "Puerto Rico",
		"QA": "Qatar",
		"RE": "Reunión",
		"RO": "Rumania",
		"RU": "Rusia",
		"RW": "Ruanda",
		"BL": "San Bartolomé",
		"SH": "Santa Elena, Ascensión y Tristán de Acuña",
		"KN": "San Cristóbal y Nieves",
		"LC": "Santa Lucía",
		"PM": "San Pedro y Miquelón",
		"VC": "San Vicente y las Granadinas",
		"WS": "Samoa",
		"SM": "San Marino",
		"ST": "Santo Tomé y Príncipe",
		"SA": "Arabia Saudita",
		"SN": "Senegal",
		"RS": "Serbia",
		"SC": "Seychelles",
		"SL": "Sierra Leona",
		"SG": "Singapur",
		"SK": "Eslovaquia",
		"SI": "Eslovenia",
		"SB": "Islas Salomón",
		"SO": "Somalia",
		"ZA": "Sudáfrica",
		"GS": "Georgia del Sur e Islas Sandwich del Sur",
		"SS": "Sudán del Sur",
		"ES": "España",
		"LK": "Sri Lanka",
		"SD": "Sudán",
		"SR": "Surinam",
		"SJ": "Svalbard y Jan Mayen",
		"SZ": "Suazilandia",
		"SE": "Suecia",
		"CH": "Suiza",
		"SY": "Siria",
		"TW": "Taiwán",
		"TJ": "Tayikistán",
		"TZ": "Tanzania",
		"TH": "Tailandia",
		"TL": "Timor Oriental",
		"TG": "Togo",
		"TK": "Tokelau",
		"TO": "Tonga",
		"TT": "Trinidad y Tobago",
		"TN": "Túnez",
		"TR": "Turquía",
		"TM": "Turkmenistán",
		"TC": "Islas Turcas y Caicos",
		"TV": "Tuvalu",
		"UG": "Uganda",
		"UA": "Ucrania",
		"AE": "Emiratos Árabes Unidos",
		"GB": "Reino Unido",
		"US": "Estados Unidos",
		"UM": "Islas Ultramarinas Menores de Estados Unidos",
		"UY": "Uruguay",
		"UZ": "Uzbekistán",
		"VU": "Vanuatu",
		"VE": "Venezuela",
		"VN": "Vietnam",
		"VG": "Islas Vírgenes Británicas",
		"VI": "Islas Vírgenes de los Estados Unidos",
		"WF": "Wallis y Futuna",
		"EH": "Sahara Occidental",
		"YE": "Yemen",
		"ZM": "Zambia",
		"ZW": "Zimbabue",
	}
)

func NumeroDePaises() int {
	return len(IndexPaises)
}

func ListaPaises() []string {
	lista := make([]string, 0, len(IndexPaises))
	for _, pais := range IndexPaises {
		lista = append(lista, pais)
	}
	return lista
}

func ListaCodigos() []string {
	lista := make([]string, 0, len(IndexPaises))
	for codigo := range IndexPaises {
		lista = append(lista, codigo)
	}
	return lista
}

func BuscarCodigo(codigo string) (string, error) {
	if pais, ok := IndexPaises[codigo]; ok {
		return pais, nil
	}
	return "", ErrorCodigoNoEncontrado
}

func BuscarNombre(nombre string) (string, error) {

	for codigo, pais := range IndexPaises {
		if pais == nombre {
			return codigo, nil
		}
	}

	return "", ErrorCodigoNoEncontrado
}
